services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: rinha
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/db.sql
