// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Person struct {
	ID        string
	Name      pgtype.Text
	Nickname  pgtype.Text
	Birthdate interface{}
	Stacks    []byte
}
